version: '3'

volumes:
  postgres_data: {}

services:

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./django
    command: >
      sh -c "python ./wait_for_postgres.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db