version: '3'

volumes:
  postgres_data: {}
  vault_file: {}
  vault_logs: {}

services:

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - vault
    env_file: ./variables.env

  django:
    build:
      context: ./django
    command: >
      sh -c "python ./wait_for_postgres.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - vault
    env_file: ./variables.env

  vault:
    image: vault:1.1.2
    command: server
    volumes:
      - ./vault/config:/vault/config
      - vault_file:/vault/file
      - vault_logs:/vault/logs
    env_file: ./variables.env
    cap_add:
      - IPC_LOCK